### ISSUE TITLE
Collect translations

### ISSUE THREAD

**Issue by sebrock** [sebrock/banano-donate#5]
# Total number of Languages: 19 (Locales covered: 21)
## Phase 1 - 8 locales

- [x] de - German
- [x] en - English
- [x] es - Spanish
- [x] es_419 - Spanish (Latin America and Caribbean)
- [x] fr - French
- [x] it - Italian
- [x] pt - Portuguese
- [x] pt_BR -Portuguese (Brazil)*

## Phase 2 - 8 locales

- [x] ar - Arabic
- [x] da - Danish
- [x] fa - Persian (Farsi)
- [x] id - Bahasa Indonesia
- [x] nl - Dutch
- [x] ru - Russian
- [x] tr - Turkish
- [x] no - Norwegian

## Phase 3 - 5 locales

- [x] el - Greek
- [x] hi - Hindi
- [x] ja - Japanese
~~- [ ] vi - Vietnamese~~ Vietnamese moved to #15 
- [x] zh_CN - Chinese (China)

**Comment by sebrock** [comment]
Phase 1 and 2 languages collected and reviewed.

**Comment by sebrock** [comment]
Vietnamese moved to #15
